### ISSUE TITLE
Create a Handwritten Digit Recognition model using the S3 extension to retrain model using the prediction.

### ISSUE THREAD

**Issue by tgcgowtham** [gowthamchanduthota/scikit-learn-aws-s3-extension#14]
#Estimated Time: Medium (5 Days)

#Acceptance Criteria:

GUI to display digit recognition, re train model using the prediction. Used to Demo S3 Integration end-to-end.

**Comment by gowthamchanduthota** [comment]
Demoes and testing with unit tests and integration tests.
